FROM microsoft/iis

MAINTAINER Jared Atkinson <jared@invoke-ir.com>

# Add and install the ASP.NET Core Module
ADD DotNetCore.1.0.5_1.1.2-WindowsHosting.exe /DotNetCore.1.0.5_1.1.2-WindowsHosting.exe
RUN DotNetCore.1.0.5_1.1.2-WindowsHosting.exe /quiet

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

EXPOSE 80 443

ENV passphrase CHANGEME!!
ENV dnsname ace.local

WORKDIR c:\\Windows\\Temp

ADD ACEWebService /inetpub/ACEWebService

COPY start.ps1 .

RUN powershell -NoProfile -File C:\windows\temp\start.ps1 -DnsName $env:dnsname -Passphrase $env:passphrase

#CMD C:\windows\temp\start.ps1 -DnsName $env:dnsname -Passphrase $env:passphrase -Verbose