FROM microsoft/mssql-server-windows

MAINTAINER Jared Atkinson <jared@invoke-ir.com>

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]

EXPOSE 1433

ENV sa_password _

WORKDIR c:\\windows\\temp

COPY start.ps1 .

COPY ace.sql .

CMD ./start.ps1 -sa_password $env:sa_password -Verbose